apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifik.fullname" . }}-config
  labels:
    {{- include "notifik.labels" . | nindent 4 }}
data:
  notifik.yaml: |
    {{- with .Values.configuration }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
