{{- if and (.Values.controller.metrics.enabled) (.Values.controller.metrics.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifik.fullname" . }}-metrics
  labels:
    {{- include "notifik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.metrics.service.type }}
  ports:
    - port: {{ .Values.controller.metrics.service.port }}
      name: metrics
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "notifik.selectorLabels" . | nindent 4 }}

{{- end }}
