---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifik.freepik.com
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notifik.freepik.com
  resources:
  - notifications/finalizers
  verbs:
  - update
- apiGroups:
  - notifik.freepik.com
  resources:
  - notifications/status
  verbs:
  - get
  - patch
  - update
