apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "notifik.fullname" . }}-manager
  labels:
    {{- include "notifik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "notifik.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "notifik.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
